version: "3.8"
services:
  postgres-db:
    container_name: vehicles
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vehicles
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5435:5432"
volumes:
    postgres_data:
      driver: local
