spring:
  application:
    name: vehicles

  datasource:
    url: jdbc:postgresql://localhost:5435/vehicles
    driver-class-name: org.postgresql.Driver
    username: dev
    password: password
  jpa:
    generated-ddl: false
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    location: classpath:db/migration
