spring:
  application:
    name: vehicles
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/vehicles
    username: dev
    password: password
  data:
    rest:
      base-path: /api
